# Generated by Django 4.1.7 on 2023-06-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='quetion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scl', to='app.quetions'),
        ),
    ]
